runtime: nodejs16

instance_class: F2

env_variables:
  BUCKET_NAME: "to-do-app-bucket"

handlers:
  - url: /
    static_files: dist/to-do-app/index.html
    upload: dist/to-do-app/index.html

  - url: /
    static_dir: dist/to-do-app
